# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'SampleExample' do
  
  # Comment the next line if you don't want to use dynamic frameworks
  
  use_frameworks!
  
  # Pods for SampleExample
  # pod 'CountryPickerAKS', '~> 0.2' # Specific Version
  # pod 'CountryPickerAKS'
  pod 'CountryPickerAKS', :path => '../' #Local

end
